In [2]:
import time

In [3]:
time.time?

Docstring:
time() -> floating point number

Return the current time in seconds since the Epoch.
Fractions of a second may be present if the system clock provides them.
Type:      builtin_function_or_method


In [6]:
print(time.time())  # prints the time stamp

1624802048.7827735


In [7]:
start = time.time()

In [8]:
end = time.time()

In [9]:
print('duration is', end - start, 'seconds')

duration is 10.867595911026001 seconds


In [10]:
my_list = list(range(1000000))
start = time.time()
new_list = map(lambda x: x*x, my_list)
end = time.time()
print(end-start)

0.522681713104248


In [11]:
my_tuple = tuple(range(1000000))
start = time.time()
new_tuple = map(lambda x: x*x, my_tuple)
end = time.time()
print(end-start)

0.0010008811950683594


In [12]:
# from the observation we can see that tuples are much faster than lists

# Sets

1. Only contains unique numbers
2. Denoted with {}
3. We can convert a list into set using set()

my_list = list(range(1000000))
start = time.time()
new_list = map(lambda x: x*x, my_list)
end = time.time()
print(end-start)

In [15]:
ml = list(range(100000000))
start = time.time()
new_list = map(lambda x: x*x, ml)
end = time.time()
print(end-start)

4.330495357513428


In [18]:
set1 = set(range(100000000))
start = time.time()
new_set = map(lambda x: x*x, set1)
end = time.time()
print(end-start)

17.21575117111206


In [19]:
print(9999 in set1)

True


# Dict

1. 

# NumPy

In [32]:
import numpy as np

In [33]:
list1 = [1,2,3]


In [34]:
type(list1)

list

In [35]:
arr1 = np.asarray(list1)

In [37]:
type(arr1)

numpy.ndarray

In [38]:
arr1.shape

(3,)

In [39]:
X = np.zeros((4,5))

In [40]:
X

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
x = np.eye((4))
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:
a =  np.random.random((4,5))

In [45]:
a

array([[0.22112383, 0.22369178, 0.01029542, 0.77680815, 0.2035856 ],
       [0.43206686, 0.46024113, 0.62117157, 0.6964837 , 0.47394537],
       [0.50398831, 0.40880797, 0.9641578 , 0.87466918, 0.32384322],
       [0.78182843, 0.98237554, 0.02014831, 0.88365606, 0.80063067]])

In [46]:
a.reshape(10,2)


array([[0.22112383, 0.22369178],
       [0.01029542, 0.77680815],
       [0.2035856 , 0.43206686],
       [0.46024113, 0.62117157],
       [0.6964837 , 0.47394537],
       [0.50398831, 0.40880797],
       [0.9641578 , 0.87466918],
       [0.32384322, 0.78182843],
       [0.98237554, 0.02014831],
       [0.88365606, 0.80063067]])

In [48]:
a.reshape(9,10)

AttributeError: 'numpy.ndarray' object has no attribute 'np'